
// FAQ page translations
const faq: Record<string, string> = {
  "Frequently Asked Questions": "Preguntas Frecuentes",
  "Still have questions?": "¿Todavía tienes preguntas?",
  "If you couldn't find the answer to your question in our FAQ, please feel free to contact our support team. We're here to help you with any inquiries related to properties, neighborhoods, or using our platform.": "Si no pudiste encontrar la respuesta a tu pregunta en nuestras FAQ, no dudes en contactar a nuestro equipo de soporte. Estamos aquí para ayudarte con cualquier consulta relacionada con propiedades, vecindarios o el uso de nuestra plataforma.",
  "Contact Support": "Contactar Soporte",
  "What kind of properties can I find on this platform?": "¿Qué tipo de propiedades puedo encontrar en esta plataforma?",
  "Our platform offers a wide range of residential and commercial properties across Athens and the surrounding regions. This includes apartments, houses, villas, office spaces, and retail properties. Each listing provides detailed information about the property, including price, location, size, and features.": "Nuestra plataforma ofrece una amplia gama de propiedades residenciales y comerciales en Atenas y las regiones circundantes. Esto incluye apartamentos, casas, villas, espacios de oficinas y propiedades comerciales. Cada listado proporciona información detallada sobre la propiedad, incluyendo precio, ubicación, tamaño y características.",
  "How can I filter properties by neighborhood?": "¿Cómo puedo filtrar propiedades por vecindario?",
  "You can use the Athens Regions selector on the home page to choose specific neighborhoods you're interested in. Simply click on the neighborhoods you want to explore, and the property listings will be filtered accordingly. You can select multiple neighborhoods to broaden your search. Additionally, you can visit the Analytics page for more detailed information and comparison between different neighborhoods.": "Puedes usar el selector de Regiones de Atenas en la página principal para elegir vecindarios específicos que te interesen. Simplemente haz clic en los vecindarios que quieres explorar, y los listados de propiedades se filtrarán en consecuencia. Puedes seleccionar múltiples vecindarios para ampliar tu búsqueda. Además, puedes visitar la página de Análisis para obtener información más detallada y comparar diferentes vecindarios.",
  "How accurate are the property prices?": "¿Qué tan precisos son los precios de las propiedades?",
  "All property prices listed on our platform are provided directly by property owners or real estate agencies. We also provide historical price data and price forecasts based on market trends to help you make informed decisions. However, final prices may be subject to negotiation between buyers and sellers.": "Todos los precios de propiedades listados en nuestra plataforma son proporcionados directamente por los propietarios o agencias inmobiliarias. También proporcionamos datos históricos de precios y pronósticos basados en tendencias del mercado para ayudarte a tomar decisiones informadas. Sin embargo, los precios finales pueden estar sujetos a negociación entre compradores y vendedores.",
  "How do I contact a property owner?": "¿Cómo contacto a un propietario?",
  "To contact a property owner, you would need to reach out to the administrator through the 'Contact Support' button at the bottom of this page. The administrator will help facilitate communication with the property owner for the specific property that interests you.": "Para contactar a un propietario, necesitas comunicarte con el administrador a través del botón 'Contactar Soporte' en la parte inferior de esta página. El administrador te ayudará a facilitar la comunicación con el propietario de la propiedad específica que te interesa.",
  "What do the neighborhood scores mean?": "¿Qué significan las puntuaciones de vecindario?",
  "Neighborhood scores are ratings from 1-10 that evaluate various aspects of each area, including walkability, safety, education, green spaces, entertainment, and retail options. These scores are calculated based on data from multiple sources and user feedback to give you a comprehensive understanding of each neighborhood's qualities.": "Las puntuaciones de vecindario son calificaciones del 1 al 10 que evalúan varios aspectos de cada área, incluyendo transitabilidad, seguridad, educación, espacios verdes, entretenimiento y opciones comerciales. Estas puntuaciones se calculan basadas en datos de múltiples fuentes y comentarios de usuarios para darte una comprensión completa de las cualidades de cada vecindario.",
  "Can I save properties to view later?": "¿Puedo guardar propiedades para ver más tarde?",
  "Yes, you can save properties to your favorites list by clicking the heart icon on any property card. To access your saved properties later, simply go to the 'Favorites' section in the sidebar menu. You'll need to be logged in to use this feature.": "Sí, puedes guardar propiedades en tu lista de favoritos haciendo clic en el icono de corazón en cualquier tarjeta de propiedad. Para acceder a tus propiedades guardadas más tarde, simplemente ve a la sección 'Favoritos' en el menú lateral. Necesitarás iniciar sesión para usar esta función.",
  "How can I upload my own property for sale?": "¿Cómo puedo subir mi propia propiedad para vender?",
  "To list a property for sale, you would need to contact the administrator through the 'Contact Support' button at the bottom of this page. Our team will guide you through the process of submitting your property details and ensure it meets our quality standards before listing it on the platform.": "Para listar una propiedad para vender, necesitas contactar al administrador a través del botón 'Contactar Soporte' en la parte inferior de esta página. Nuestro equipo te guiará a través del proceso de envío de los detalles de tu propiedad y se asegurará de que cumpla con nuestros estándares de calidad antes de listarla en la plataforma.",
  "What is the Loan Calculator used for?": "¿Para qué se usa la Calculadora de Préstamos?",
  "The Loan Calculator helps you estimate monthly mortgage payments based on property price, down payment, interest rate, and loan term. It's a useful tool for understanding the financial commitment required for properties you're interested in. You can access it by clicking 'Loan Calculator' in the sidebar.": "La Calculadora de Préstamos te ayuda a estimar los pagos mensuales de hipoteca basados en el precio de la propiedad, el pago inicial, la tasa de interés y el plazo del préstamo. Es una herramienta útil para entender el compromiso financiero requerido para las propiedades que te interesan. Puedes acceder a ella haciendo clic en 'Calculadora de Préstamos' en la barra lateral.",
  "How can I compare different neighborhoods?": "¿Cómo puedo comparar diferentes vecindarios?",
  "Our platform offers detailed analytics on different regions and neighborhoods. You can compare price trends, property types, and neighborhood scores by visiting the 'Analytics' section. You can also view specific region details by clicking on any region name throughout the platform.": "Nuestra plataforma ofrece análisis detallados sobre diferentes regiones y vecindarios. Puedes comparar tendencias de precios, tipos de propiedades y puntuaciones de vecindarios visitando la sección 'Análisis'. También puedes ver detalles específicos de una región haciendo clic en cualquier nombre de región a lo largo de la plataforma.",
  "Is there a mobile version of this platform?": "¿Existe una versión móvil de esta plataforma?",
  "Currently, there is not a mobile version of our platform, but it is being developed. In the meantime, you can access our website through your mobile browser, though some complex analytics visualizations may display better on larger screens.": "Actualmente, no hay una versión móvil de nuestra plataforma, pero está en desarrollo. Mientras tanto, puedes acceder a nuestro sitio web a través de tu navegador móvil, aunque algunas visualizaciones analíticas complejas pueden mostrarse mejor en pantallas más grandes."
};

export default faq;
