server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: real-estate-tool-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://${supabase.url}/auth/v1/keys

supabase:
  url: ${supabase.url}
  anon-key: ${supabase.anon-key}
  service-role-key: ${supabase.service-role-key}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  health:
    diskspace:
      enabled: true
    db:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  paths-to-match: /api/**

logging:
  level:
    com.realestatetool: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
